### PR TITLE
style: added brplusa logo to index.html

### PR DESCRIPTION
**Pull request by TfedUD**
why email a logo when you can send a PR!

### CODE REVIEW

**Comment by mostaphaRoudsari** [comment]
Hi @TfedUD! Thank you for the PR. I have two minor comments:

1. Can we remove the background in the image?
2. Can we move it after the one for Transsolar and also add a bit of additional border to it so it doesn't touch the edge of the container?

image

**Comment by TfedUD** [comment]
Yeah for sure! I can make those edits shortly!

**Comment by TfedUD** [comment]
@mostaphaRoudsari done! new *.png and updated the logo arrangement

**Comment by mostaphaRoudsari** [comment]
Merged!

**Pull request merged**
